version: '3'

rpc:
  listen: tcp://${OCTANE_RR_RPC_HOST}:${OCTANE_RR_RPC_PORT}

server:
  command: "php vendor/bin/roadrunner-worker"

http:
  address: ${OCTANE_RR_HOST}:${OCTANE_RR_PORT}
  pool:
    num_workers: ${OCTANE_RR_WORKERS}
    max_jobs: ${OCTANE_RR_MAX_REQUESTS}
    supervisor:
      max_worker_memory: 128
  static:
    dir: '/public'

grpc:
  address: ${OCTANE_RR_HOST}:${OCTANE_RR_PORT}
  pool:
    num_workers: ${OCTANE_RR_WORKERS}
    max_jobs: ${OCTANE_RR_MAX_REQUESTS}

jobs:
  consume: [ "default" ]
  pool:
    num_workers: 2
    supervisor:
      max_worker_memory: 100
  pipelines:
    default:
      driver: memory
      config:
        priority: 10
