<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/proto/collector.proto

namespace GRPC\TraceCollector;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trace.collector.TraceProfilingItemDataItemObject</code>
 */
class TraceProfilingItemDataItemObject extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>.trace.collector.TraceProfilingItemDataItemValueObject value = 2;</code>
     */
    protected $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \GRPC\TraceCollector\TraceProfilingItemDataItemValueObject $value
     * }
     */
    public function __construct($data = NULL) {
        \GRPC\TraceCollectorGPBMetadata\Collector::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.trace.collector.TraceProfilingItemDataItemValueObject value = 2;</code>
     * @return \GRPC\TraceCollector\TraceProfilingItemDataItemValueObject
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>.trace.collector.TraceProfilingItemDataItemValueObject value = 2;</code>
     * @param \GRPC\TraceCollector\TraceProfilingItemDataItemValueObject $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \GRPC\TraceCollector\TraceProfilingItemDataItemValueObject::class);
        $this->value = $var;

        return $this;
    }

}

