<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/proto/collector.proto

namespace GRPC\TraceCollector;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trace.collector.TraceProfilingItemDataItemValueObject</code>
 */
class TraceProfilingItemDataItemValueObject extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.DoubleValue double = 1;</code>
     */
    protected $double = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value int = 2;</code>
     */
    protected $int = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\DoubleValue $double
     *     @type \Google\Protobuf\Int32Value $int
     * }
     */
    public function __construct($data = NULL) {
        \GRPC\TraceCollectorGPBMetadata\Collector::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.DoubleValue double = 1;</code>
     * @return \Google\Protobuf\DoubleValue
     */
    public function getDouble()
    {
        return $this->double;
    }

    /**
     * Returns the unboxed value from <code>getDouble()</code>

     * Generated from protobuf field <code>.google.protobuf.DoubleValue double = 1;</code>
     * @return float|null
     */
    public function getDoubleUnwrapped()
    {
        return $this->readWrapperValue("double");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.DoubleValue double = 1;</code>
     * @param \Google\Protobuf\DoubleValue $var
     * @return $this
     */
    public function setDouble($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\DoubleValue::class);
        $this->double = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\DoubleValue object.

     * Generated from protobuf field <code>.google.protobuf.DoubleValue double = 1;</code>
     * @param float|null $var
     * @return $this
     */
    public function setDoubleUnwrapped($var)
    {
        $this->writeWrapperValue("double", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value int = 2;</code>
     * @return \Google\Protobuf\Int32Value
     */
    public function getInt()
    {
        return $this->int;
    }

    /**
     * Returns the unboxed value from <code>getInt()</code>

     * Generated from protobuf field <code>.google.protobuf.Int32Value int = 2;</code>
     * @return int|null
     */
    public function getIntUnwrapped()
    {
        return $this->readWrapperValue("int");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value int = 2;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setInt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->int = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * Generated from protobuf field <code>.google.protobuf.Int32Value int = 2;</code>
     * @param int|null $var
     * @return $this
     */
    public function setIntUnwrapped($var)
    {
        $this->writeWrapperValue("int", $var);
        return $this;}

}

