<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/proto/collector.proto

namespace GRPC\TraceCollector;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trace.collector.TraceCreateRequest</code>
 */
class TraceCreateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .trace.collector.TraceCreateObject traces = 1;</code>
     */
    private $traces;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \GRPC\TraceCollector\TraceCreateObject[]|\Google\Protobuf\Internal\RepeatedField $traces
     * }
     */
    public function __construct($data = NULL) {
        \GRPC\TraceCollectorGPBMetadata\Collector::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .trace.collector.TraceCreateObject traces = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTraces()
    {
        return $this->traces;
    }

    /**
     * Generated from protobuf field <code>repeated .trace.collector.TraceCreateObject traces = 1;</code>
     * @param \GRPC\TraceCollector\TraceCreateObject[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTraces($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GRPC\TraceCollector\TraceCreateObject::class);
        $this->traces = $arr;

        return $this;
    }

}

